replicaCount: 1

namespace: "testing"

app:
  environment: "test"
  owner : "Microsoft"
  name: "codeless-attach-polyglot"
  node:
    name: "fabrikam-aks-nodejs"
  java: 
    name: "fabrikam-notifier-aks-java"
  netcore:
    name: "fabrikam-backend-core"
  go:
    name: "fabrikam-worker-go-oc"  

nodeSelector: "{ \"beta.kubernetes.io/os\": linux }"