apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.node.name }}
  {{- template "common.metadata" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 50030
  selector:
    app: {{ .Values.app.node.name }}