apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.netcore.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  {{- template "common.metadata" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.app.netcore.name }}