apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.localForwarder.nameOC }}
  {{- template "common.metadata" . }}
spec:
  selector:
    app: {{ .Values.localForwarder.name }}
  type: LoadBalancer
  ports:
  - name: http-port-oc
    protocol: TCP
    port: {{ .Values.localForwarder.portOC }}
    targetPort: {{ .Values.localForwarder.portOC }}