{{- range .Values.namespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: attach-config
  namespace: {{ .target }}
  {{- template "common.metadata" $ }}
data:
  ikey: {{ .iKey }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns-{{ .target }}
  namespace: {{ .target }}
  {{- template "common.metadata" $ }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: labeler-{{ .target }}
        image: gcr.io/google_containers/hyperkube:v1.9.7
        command:
        - kubectl
        - label
        - ns
        - {{ .target }}
        - mutating-webhook=enabled
        - --overwrite
      restartPolicy: Never
---
{{- end }}