{{ $p2 := .Values.connection.p2 }}
{{ $p3 := .Values.connection.p3 }}
{{- range .Values.namespaces }}
{{ $concatenated := printf "%s%s%s" $p2 .iKey $p3 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: attach-config
  namespace: {{ .target }}
  {{- template "common.labels" $ }}
data:
  ikey: {{ .iKey }}
  connectionString: {{ $concatenated }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-ns-{{ .target }}
  namespace: {{ .target }}
  {{- template "common.labels" $ }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: labeler-{{ .target }}
        image: gcr.io/google_containers/hyperkube:v1.9.7
        command:
        - kubectl
        - label
        - ns
        - {{ .target }}
        - mutating-webhook=enabled
        - --overwrite
      restartPolicy: Never
---
{{- end }}