apiVersion: v1
kind: ConfigMap
metadata:
  name: attach-config
  namespace: {{ .Values.namespace }}
  labels: 
    environment: {{ .Values.app.environment }}
    owner: {{ .Values.app.owner }}
    app: {{ .Values.app.name }}
data:
  ikey: {{ .Values.app.ikey }}