apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.disk.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: {{ .Values.disk.size }}
  volumeMode: Filesystem