apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.disk.name }}
  {{- template "common.metadata" . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: {{ .Values.disk.size }}