apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    version: {{ .Chart.Version }}
    environment: {{ .Values.app.environment }}
    owner: {{ .Values.app.owner }}
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: 
        version: {{ .Chart.Version }}
        environment: {{ .Values.app.environment }}
        owner: {{ .Values.app.owner }}
        app: {{ .Values.app.name }}
    spec:
      nodeSelector: {{ .Values.app.nodeSelector }}
      containers:
        - name: {{ .Values.app.name }}
          image: mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook:dev7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.app.name }}
