apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  {{- template "common.metadata" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- template "common.metadata" . }}
    spec:
      nodeSelector: {{ .Values.app.nodeSelector }}
      containers:
        - name: {{ .Values.app.name }}
          image: mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook:dev7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.app.name }}
