apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-disk
  namespace: aks-webhook-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 1Gi