apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: mutating-webhook.this.svc
    clientConfig:
      service:
        name: mutating-webhook
        namespace: mutating-webhook-ns
        path: "/"
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        mutating-webhook: enabled