apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mutating-webhook
  namespace: aks-webhook-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: mutating-webhook
          image: gearamaaks.azurecr.io/webhook/mutating-webhook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
            - mountPath: "/mnt/agent-disk"
              name: agent-volume
      volumes:
        - name: webhook-certs
          secret:
            secretName: aks-webhook
        - name: agent-volume
          persistentVolumeClaim:
            claimName: agent-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
spec:
  type: LoadBalancer
  ports:
    - port: 1337
  selector:
    app: mutating-webhook