apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mutating-webhook
  namespace: aks-webhook-ns
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: mutating-webhook
          image: mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook:dev5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: aks-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
  namespace: aks-webhook-ns
spec:
  type: LoadBalancer
  ports:
    - port: 47777
      protocol: TCP
      targetPort: 1337
  selector:
    app: mutating-webhook