replicaCount: 1

app:
  environment: "test"
  owner : "Microsoft"
  name: "codeless-attach-polyglot"
  node:
    image: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/nodejs-sample:v46"
    name: "codeless-attach-nodejs"
  java: 
    image: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/java-sample:v46"
    name: "codeless-attach-java"
  netcore:
    image: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/netcore-sample:v46"
    name: "codeless-attach-core"
env:
  connStr: "DefaultEndpointsProtocol=https;AccountName=gearamacodeless1;AccountKey=dnrXQq43kNQ2pzDImxhVfQS9GuMJx9a/nbtF+BXA2/GSIvT8157CS6crH7ldQYNKXW9SmiIUkbT7eVr7QADlCQ==;EndpointSuffix=core.windows.net"

nodeSelector: "{ \"beta.kubernetes.io/os\": linux }"