{{- range .Values.namespaces }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.localForwarder.name }}-{{ .target }}
  namespace: {{ quote .target }}
  {{- template "common.labels" $ }}
spec:
  selector:
    app: {{ $.Values.localForwarder.name }}-{{ .target }}
  #type: LoadBalancer
  ports:
  - name: http-port
    protocol: TCP
    port: {{ $.Values.localForwarder.port }}
    targetPort: {{ $.Values.localForwarder.port }}
---
{{- end }}