{{- range .Values.namespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.labeler.account }}
  namespace: {{ quote .target }}
  {{- template "common.labels" $ }}
---
{{- end }}