{{- range .Values.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.labeler.account }}-{{ .target }}-binding
  namespace: {{ quote .target }}
  {{- template "common.labels" $ }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.labeler.account }}
  namespace: {{ .target }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.app.name }}-{{ quote .target }}-binding
  namespace: {{ quote .target }}
  {{- template "common.labels" $ }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.app.name }}
  namespace: {{ $.Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}