{{- range .Values.namespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: attach-config
  namespace: {{ quote .target }}
  {{- template "common.labels" $ }}
data:
  ikey: {{ .iKey }}
---
{{- end }}