apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels: 
    environment: {{ .Values.app.environment }}
    owner: {{ .Values.app.owner }}
    app: {{ .Values.app.name }}


