# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "aks-webhook-ns"

namespaces: 
  - target : "default"
    iKey: "a35e0710-201e-44bb-a3a7-9b559277ca6d"

app:
  name: "mutating-webhook"
  environment: "test"
  owner : "Microsoft"
  image: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/mutating-webhook:v75"
  agents: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/mutating-webhook-agents:v31"

replicaCount: 1

localForwarder: 
  image: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/local-forwarder:v10"
  name: "localforwarder"
  nameAI: "localforwarder"
  portAI: 50001
  nameOC: "localforwarder-oc"
  portOC: 50002
  iKey: "a35e0710-201e-44bb-a3a7-9b559277ca6d"
  liveMetricsAuthKey: " "
  adaptiveSamplingLimit: 5
  replicas: 1

connection: 
  p2: "InstrumentationKey="
  p3: ";IngestionEndpoint=http://10.240.0.10"

nodeSelector: "{ \"beta.kubernetes.io/os\": linux }"