# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "aks-webhook-ns"

namespaces: 
  - target : "<taget namespace>"
    iKey: "target ikey"

app:
  name: "mutating-webhook"
  environment: "test"
  owner : "Microsoft"
  image: "mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook:preview1"
  agents: "mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook-agents:preview1"
  caBundle: "baseBundle"

labeler: 
  account: labeler
  
replicaCount: 1

nodeSelector: "{ \"beta.kubernetes.io/os\": linux }"