apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.localForwarder.nameAI }}
  {{- template "common.metadata" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: {{ .Values.localForwarder.nameAI }}
  type: LoadBalancer
  ports:
  - name: http-port-ai
    protocol: TCP
    port: 80
    targetPort: {{ .Values.localForwarder.portAI }}
